### ISSUE TITLE
[BUG] Blocks don't break properly when in Space

### ISSUE THREAD

**Issue by ghost** [shazean/CelestialExploration#2]
When I'm in Space and try to break or place blocks they break and then imedietly come back. And sometimes I spawn in space not in the Space Ship and that is what proceds this issue.

**Comment by shazean** [comment]
Yeah, there's a glitch with the spaceship not loading when you teleport sometimes, and then if you continue on without waiting for it catch up, it'll cause further glitches.  I suspect it's a client/server discrepancy, but I haven't narrowed it down yet.
I'll add this to my list of bugs to fix.

**Comment by shazean** [comment]
This should be fixed in the 0.7.0 update

**Comment by shazean** [comment]
This should be fixed in the 0.7.0 update
